name: Build and upload release

on:
  release:
    types: [created]

env:
  APP_NAME: code-runner
  ARCHIVE_NAME: code-runner_linux-x64.tar.gz

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build application
        run: |
          cargo build --release
          tar -czf $ARCHIVE_NAME -C target/release $APP_NAME

      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ github.event.release.tag_name }}" "$ARCHIVE_NAME" --clobber
